---

- name: Fetch genesis.json
  fetch: "src=/home/meled/.meled/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: meled

- name: Fetch config.toml
  fetch: "src=/home/meled/.meled/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: meled
